### ISSUE TITLE
Question: why do we filter messages?

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-clique/clap-verbosity-flag#6]
@killercup you're probably the right person to ask, but: why are we filtering messages in [`.setup_env_logger()`](https://github.com/rust-clique/clap-verbosity-flag/blob/master/src/lib.rs#L57-L61)?

I can imagine it being useful to sometimes log out trace messages from library code (e.g. embedded databases, etc.) Should we perhaps introduce a method / flag that doesn't filter?

**Comment by killercup** [comment]
It is my understanding that this is a good default and that it can be overwritten by setting the RUST_LOG env var to something like `RUST_LOG=foo=trace`. Haven't looked at this in a while though

**Comment by yoshuawuyts** [comment]
@killercup ahh yeah, that answers it. Thanks!

**Comment by killercup** [comment]
Would be awesome to document that too :)
